# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-02-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mydate_f', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
